// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name, imap_host, imap_port, imap_user, imap_password,
    smtp_host, smtp_port, smtp_user, smtp_password
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, imap_host, imap_port, imap_user, imap_password, smtp_host, smtp_port, smtp_user, smtp_password, created_at
`

type CreateAccountParams struct {
	Name         string  `json:"name"`
	ImapHost     string  `json:"imap_host"`
	ImapPort     int32   `json:"imap_port"`
	ImapUser     string  `json:"imap_user"`
	ImapPassword string  `json:"imap_password"`
	SmtpHost     *string `json:"smtp_host"`
	SmtpPort     *int32  `json:"smtp_port"`
	SmtpUser     *string `json:"smtp_user"`
	SmtpPassword *string `json:"smtp_password"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapUser,
		arg.ImapPassword,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUser,
		arg.SmtpPassword,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUser,
		&i.ImapPassword,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUser,
		&i.SmtpPassword,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, imap_host, imap_port, imap_user, imap_password, smtp_host, smtp_port, smtp_user, smtp_password, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUser,
		&i.ImapPassword,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUser,
		&i.SmtpPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, imap_host, imap_port, imap_user, imap_password, smtp_host, smtp_port, smtp_user, smtp_password, created_at FROM accounts ORDER BY created_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapUser,
			&i.ImapPassword,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUser,
			&i.SmtpPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
