// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAttachmentsByEmailID = `-- name: DeleteAttachmentsByEmailID :exec
DELETE FROM attachments WHERE email_id = $1
`

func (q *Queries) DeleteAttachmentsByEmailID(ctx context.Context, emailID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByEmailID, emailID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, email_id, filename, content_type, size, s3_key FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.S3Key,
	)
	return i, err
}

const getAttachmentsByEmailID = `-- name: GetAttachmentsByEmailID :many
SELECT id, email_id, filename, content_type, size, s3_key FROM attachments WHERE email_id = $1
`

func (q *Queries) GetAttachmentsByEmailID(ctx context.Context, emailID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByEmailID, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.S3Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (
    email_id, filename, content_type, size, s3_key
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email_id, filename, content_type, size, s3_key
`

type InsertAttachmentParams struct {
	EmailID     pgtype.UUID `json:"email_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	Size        int64       `json:"size"`
	S3Key       string      `json:"s3_key"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.EmailID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.S3Key,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.S3Key,
	)
	return i, err
}
