// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailsInFolder = `-- name: CountEmailsInFolder :one
SELECT COUNT(*) FROM emails
WHERE account_id = $1 AND folder = $2 AND deleted_upstream = false
`

type CountEmailsInFolderParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Folder    string      `json:"folder"`
}

func (q *Queries) CountEmailsInFolder(ctx context.Context, arg CountEmailsInFolderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailsInFolder, arg.AccountID, arg.Folder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const emailExistsByMessageID = `-- name: EmailExistsByMessageID :one
SELECT EXISTS(
    SELECT 1 FROM emails
    WHERE account_id = $1 AND message_id = $2
) AS exists
`

type EmailExistsByMessageIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	MessageID *string     `json:"message_id"`
}

func (q *Queries) EmailExistsByMessageID(ctx context.Context, arg EmailExistsByMessageIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailExistsByMessageID, arg.AccountID, arg.MessageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const emailExistsByUID = `-- name: EmailExistsByUID :one
SELECT EXISTS(
    SELECT 1 FROM emails
    WHERE account_id = $1 AND folder = $2 AND uid = $3
) AS exists
`

type EmailExistsByUIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Folder    string      `json:"folder"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) EmailExistsByUID(ctx context.Context, arg EmailExistsByUIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailExistsByUID, arg.AccountID, arg.Folder, arg.Uid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEmail = `-- name: GetEmail :one
SELECT id, account_id, uid, message_id, folder, subject, from_email, from_name, date, parsed_text, parsed_html, raw, flags, deleted_upstream, search_vector, created_at, to_recipients, cc_recipients FROM emails WHERE id = $1
`

func (q *Queries) GetEmail(ctx context.Context, id pgtype.UUID) (Email, error) {
	row := q.db.QueryRow(ctx, getEmail, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uid,
		&i.MessageID,
		&i.Folder,
		&i.Subject,
		&i.FromEmail,
		&i.FromName,
		&i.Date,
		&i.ParsedText,
		&i.ParsedHtml,
		&i.Raw,
		&i.Flags,
		&i.DeletedUpstream,
		&i.SearchVector,
		&i.CreatedAt,
		&i.ToRecipients,
		&i.CcRecipients,
	)
	return i, err
}

const getEmailByUID = `-- name: GetEmailByUID :one
SELECT id, account_id, uid, message_id, folder, subject, from_email, from_name, date, parsed_text, parsed_html, raw, flags, deleted_upstream, search_vector, created_at, to_recipients, cc_recipients FROM emails
WHERE account_id = $1 AND folder = $2 AND uid = $3
`

type GetEmailByUIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Folder    string      `json:"folder"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) GetEmailByUID(ctx context.Context, arg GetEmailByUIDParams) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByUID, arg.AccountID, arg.Folder, arg.Uid)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uid,
		&i.MessageID,
		&i.Folder,
		&i.Subject,
		&i.FromEmail,
		&i.FromName,
		&i.Date,
		&i.ParsedText,
		&i.ParsedHtml,
		&i.Raw,
		&i.Flags,
		&i.DeletedUpstream,
		&i.SearchVector,
		&i.CreatedAt,
		&i.ToRecipients,
		&i.CcRecipients,
	)
	return i, err
}

const insertEmail = `-- name: InsertEmail :one
INSERT INTO emails (
    account_id, uid, message_id, folder, subject,
    from_email, from_name, to_recipients, cc_recipients,
    date, parsed_text, parsed_html, raw, flags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, account_id, uid, message_id, folder, subject, from_email, from_name, date, parsed_text, parsed_html, raw, flags, deleted_upstream, search_vector, created_at, to_recipients, cc_recipients
`

type InsertEmailParams struct {
	AccountID    pgtype.UUID        `json:"account_id"`
	Uid          int64              `json:"uid"`
	MessageID    *string            `json:"message_id"`
	Folder       string             `json:"folder"`
	Subject      *string            `json:"subject"`
	FromEmail    *string            `json:"from_email"`
	FromName     *string            `json:"from_name"`
	ToRecipients []byte             `json:"to_recipients"`
	CcRecipients []byte             `json:"cc_recipients"`
	Date         pgtype.Timestamptz `json:"date"`
	ParsedText   *string            `json:"parsed_text"`
	ParsedHtml   *string            `json:"parsed_html"`
	Raw          *string            `json:"raw"`
	Flags        []string           `json:"flags"`
}

func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, insertEmail,
		arg.AccountID,
		arg.Uid,
		arg.MessageID,
		arg.Folder,
		arg.Subject,
		arg.FromEmail,
		arg.FromName,
		arg.ToRecipients,
		arg.CcRecipients,
		arg.Date,
		arg.ParsedText,
		arg.ParsedHtml,
		arg.Raw,
		arg.Flags,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Uid,
		&i.MessageID,
		&i.Folder,
		&i.Subject,
		&i.FromEmail,
		&i.FromName,
		&i.Date,
		&i.ParsedText,
		&i.ParsedHtml,
		&i.Raw,
		&i.Flags,
		&i.DeletedUpstream,
		&i.SearchVector,
		&i.CreatedAt,
		&i.ToRecipients,
		&i.CcRecipients,
	)
	return i, err
}

const listEmails = `-- name: ListEmails :many
SELECT id, account_id, uid, message_id, folder, subject, from_email, from_name, date, parsed_text, parsed_html, raw, flags, deleted_upstream, search_vector, created_at, to_recipients, cc_recipients FROM emails
WHERE account_id = $1
  AND folder = $2
  AND ($5::timestamptz IS NULL OR date < $5)
  AND ($6::timestamptz IS NULL OR date > $6)
ORDER BY date DESC
LIMIT $3 OFFSET $4
`

type ListEmailsParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Folder    string             `json:"folder"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	Before    pgtype.Timestamptz `json:"before"`
	After     pgtype.Timestamptz `json:"after"`
}

func (q *Queries) ListEmails(ctx context.Context, arg ListEmailsParams) ([]Email, error) {
	rows, err := q.db.Query(ctx, listEmails,
		arg.AccountID,
		arg.Folder,
		arg.Limit,
		arg.Offset,
		arg.Before,
		arg.After,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Email{}
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Uid,
			&i.MessageID,
			&i.Folder,
			&i.Subject,
			&i.FromEmail,
			&i.FromName,
			&i.Date,
			&i.ParsedText,
			&i.ParsedHtml,
			&i.Raw,
			&i.Flags,
			&i.DeletedUpstream,
			&i.SearchVector,
			&i.CreatedAt,
			&i.ToRecipients,
			&i.CcRecipients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailDeletedUpstream = `-- name: MarkEmailDeletedUpstream :exec
UPDATE emails SET deleted_upstream = true WHERE id = $1
`

func (q *Queries) MarkEmailDeletedUpstream(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailDeletedUpstream, id)
	return err
}

const updateEmailFlags = `-- name: UpdateEmailFlags :exec
UPDATE emails SET flags = $2 WHERE id = $1
`

type UpdateEmailFlagsParams struct {
	ID    pgtype.UUID `json:"id"`
	Flags []string    `json:"flags"`
}

func (q *Queries) UpdateEmailFlags(ctx context.Context, arg UpdateEmailFlagsParams) error {
	_, err := q.db.Exec(ctx, updateEmailFlags, arg.ID, arg.Flags)
	return err
}
