// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	ImapHost     string             `json:"imap_host"`
	ImapPort     int32              `json:"imap_port"`
	ImapUser     string             `json:"imap_user"`
	ImapPassword string             `json:"imap_password"`
	SmtpHost     *string            `json:"smtp_host"`
	SmtpPort     *int32             `json:"smtp_port"`
	SmtpUser     *string            `json:"smtp_user"`
	SmtpPassword *string            `json:"smtp_password"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Attachment struct {
	ID          pgtype.UUID `json:"id"`
	EmailID     pgtype.UUID `json:"email_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	Size        int64       `json:"size"`
	S3Key       string      `json:"s3_key"`
}

type Email struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	Uid             int64              `json:"uid"`
	MessageID       *string            `json:"message_id"`
	Folder          string             `json:"folder"`
	Subject         *string            `json:"subject"`
	FromEmail       *string            `json:"from_email"`
	FromName        *string            `json:"from_name"`
	Date            pgtype.Timestamptz `json:"date"`
	ParsedText      *string            `json:"parsed_text"`
	ParsedHtml      *string            `json:"parsed_html"`
	Raw             *string            `json:"raw"`
	Flags           []string           `json:"flags"`
	DeletedUpstream *bool              `json:"deleted_upstream"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ToRecipients    []byte             `json:"to_recipients"`
	CcRecipients    []byte             `json:"cc_recipients"`
}

type Webhook struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookQueue struct {
	ID          pgtype.UUID        `json:"id"`
	WebhookID   pgtype.UUID        `json:"webhook_id"`
	EmailID     pgtype.UUID        `json:"email_id"`
	Payload     []byte             `json:"payload"`
	Attempts    *int32             `json:"attempts"`
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
