// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookQueueItem = `-- name: CreateWebhookQueueItem :one
INSERT INTO webhook_queue (
    webhook_id, email_id, payload, status
) VALUES (
    $1, $2, $3, 'pending'
) RETURNING id, webhook_id, email_id, payload, attempts, next_attempt, status, created_at
`

type CreateWebhookQueueItemParams struct {
	WebhookID pgtype.UUID `json:"webhook_id"`
	EmailID   pgtype.UUID `json:"email_id"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) CreateWebhookQueueItem(ctx context.Context, arg CreateWebhookQueueItemParams) (WebhookQueue, error) {
	row := q.db.QueryRow(ctx, createWebhookQueueItem, arg.WebhookID, arg.EmailID, arg.Payload)
	var i WebhookQueue
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EmailID,
		&i.Payload,
		&i.Attempts,
		&i.NextAttempt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingWebhookQueueItems = `-- name: GetPendingWebhookQueueItems :many
SELECT id, webhook_id, email_id, payload, attempts, next_attempt, status, created_at FROM webhook_queue
WHERE status = 'pending' AND next_attempt <= NOW()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingWebhookQueueItems(ctx context.Context, limit int32) ([]WebhookQueue, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookQueueItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookQueue{}
	for rows.Next() {
		var i WebhookQueue
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EmailID,
			&i.Payload,
			&i.Attempts,
			&i.NextAttempt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookQueueItem = `-- name: GetWebhookQueueItem :one
SELECT id, webhook_id, email_id, payload, attempts, next_attempt, status, created_at FROM webhook_queue WHERE id = $1
`

func (q *Queries) GetWebhookQueueItem(ctx context.Context, id pgtype.UUID) (WebhookQueue, error) {
	row := q.db.QueryRow(ctx, getWebhookQueueItem, id)
	var i WebhookQueue
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EmailID,
		&i.Payload,
		&i.Attempts,
		&i.NextAttempt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markWebhookQueueDelivered = `-- name: MarkWebhookQueueDelivered :execrows
UPDATE webhook_queue
SET status = 'delivered'
WHERE id = $1
`

func (q *Queries) MarkWebhookQueueDelivered(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookQueueDelivered, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWebhookQueueFailed = `-- name: MarkWebhookQueueFailed :execrows
UPDATE webhook_queue
SET status = 'failed'
WHERE id = $1
`

func (q *Queries) MarkWebhookQueueFailed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookQueueFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookQueueStatus = `-- name: UpdateWebhookQueueStatus :execrows
UPDATE webhook_queue
SET status = $2, attempts = $3, next_attempt = $4
WHERE id = $1
`

type UpdateWebhookQueueStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Attempts    *int32             `json:"attempts"`
	NextAttempt pgtype.Timestamptz `json:"next_attempt"`
}

func (q *Queries) UpdateWebhookQueueStatus(ctx context.Context, arg UpdateWebhookQueueStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookQueueStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.NextAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
