// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    account_id, url, secret
) VALUES (
    $1, $2, $3
) RETURNING id, account_id, url, secret, created_at
`

type CreateWebhookParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Url       string      `json:"url"`
	Secret    string      `json:"secret"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook, arg.AccountID, arg.Url, arg.Secret)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, account_id, url, secret, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id pgtype.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhooksForAccount = `-- name: GetWebhooksForAccount :many
SELECT id, account_id, url, secret, created_at FROM webhooks WHERE account_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetWebhooksForAccount(ctx context.Context, accountID pgtype.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, getWebhooksForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Url,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, account_id, url, secret, created_at FROM webhooks ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Url,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
